name: Docker - Stage

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - '**/.gitignore'
      - '**/README.md'

jobs:
  docker-stage:
    uses: ./.github/workflows/docker.yml
    with:
      environment: staging
      image-name: ${{ github.repository_owner }}/webtest.vixenlights.com
    secrets: inherit
