name: Docker - Prod

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - '**/.gitignore'
      - '**/README.md'

jobs:
  docker-prod:
    uses: ./.github/workflows/docker.yml
    with:
      hugo-environment: production
      image-name: ${{ github.repository_owner }}/www.vixenlights.com
    secrets: inherit
